url: https://47.99.189.243
navbar:
  blog_title: 大王的养猪场
  menu:
    - { key: 'home', link: '/', icon: 'iconfont icon-home-fill' }
    - { key: 'tag', link: '/tags/', icon: 'iconfont icon-tags-fill' }
    - { key: 'about', link: '/about/', icon: 'iconfont icon-user-fill', name: '联系我' }
index:
  slogan:
    enable: true
    api:
      enable: true
      url: "https://v1.hitokoto.cn?c=i"
      method: "GET"
      headers: {}
      keys: ["hitokoto"]
  banner_img: /img/wallhaven-l8yl6q_1920x1080.png
post:
  katex: false
about:
  avatar: /img/avatar.jpg
  name: 大王的小猪猪
  intro: 一个热爱生活，持续学习的胖子
  icons:
    - { class: 'iconfont icon-linkedin-fill', link: 'https://www.linkedin.com/in/%E5%AE%97%E6%B3%B0-%E5%BC%A0-062754280/', tip: 'linkedin' }
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/firestige', tip: 'GitHub' }
    - { class: 'iconfont icon-zhihu-fill', link: 'https://zhihu.com/people/firestige', tip: '知乎' }
    - { class: 'iconfont icon-mail', link: 'mailto:zzt.nbl@hotmail.com', tip: '邮箱' }
    - { class: 'iconfont icon-wechat-fill', qrcode: '/img/WeChat.jpg' }
